# Generated by Django 3.2.4 on 2021-06-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feed', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('phoneNo', models.CharField(max_length=12)),
                ('tag', models.TextField(default='Happy')),
                ('feed_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedback')),
            ],
        ),
    ]
