# Generated by Django 3.2.4 on 2021-06-21 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feedback_feed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedback')),
            ],
        ),
    ]
